### ISSUE TITLE
Visible lull between waves of particles

### ISSUE THREAD

**Issue by Sky-Captain-13** [ghost-fvtt/fxmaster#122]
### Expected Behavior

* No lull between waves

### Current Behavior

* Lull between waves

![image](https://user-images.githubusercontent.com/10356477/147097707-f3a384a4-a48e-4dc5-aa23-b7c153a6a5ef.png)

Snow particles are being created on the left and as they move to the right, this creates a noticeable gap (especially at higher densities) before the next wave of particles are created.

### Steps to Reproduce

1. Add snow
2. Set to max density
3. Observe

### Version

2.0.0

### Foundry VTT Version

v9.238

### Operating System

Windows 10

### Browser / App

Native Electron App

### Game System

dnd5e

### Relevant Modules

n/a

**Comment by ghost91-** [comment]
Hey @Sky-Captain-13, I just released a new version (v2.2.0) which should fix this issue. Can you confirm the problem is gone now?

**Comment by Sky-Captain-13** [comment]
Looks like it's fixed. Thanks! The left side still shows fewer of the snowflakes, but it's not as obvious as the lulls were.

**Comment by ghost91-** [comment]
Yeah, the reason for that is that when you don’t have a padding area (which you don’t seem to have in that scene), the spawn area of the particles is just all of the scene. That means on the left side, particles will spawn, but there are no particles that move into that area, they just move out of it, so there are always less particles in that area. I will probably improve the spawn areas of effects in the future so that the spawn area is abbot larger and effects look more uniform across their visible area. But it’s actually pretty difficult to get this exactly right while not wasting tu much resources by rendering stuff outside the visible area.

**Comment by Sky-Captain-13** [comment]
Ah, yeah... I dislike having padding. So I set it to zero on every map.
