### ISSUE TITLE
Filter won't apply via macro when same sort of filter already active

### ISSUE THREAD

**Issue by Danii0206** [ghost-fvtt/fxmaster#167]
### Expected Behavior

Hi,

I use this macro:
`FXMASTER.filters.switch("redfilterID", "color", { color: {value: "#880000", apply:true}, gamma: 1.0, contrast: 1.0, brightness: 1.0, saturation: 1.0 });`

And I have already a colorfilter on the scene, with gamma:0.5 and no tint. (Set via Filter Control settings dialog.)

Expected behavior would be:
Execute it once -> scene goes red at gamma 1.0.
Execute again -> scene goes back to normal at gamma 0.5.

That is how it worked before I updated to Foundry 9 and the according FXMaster.

### Current Behavior

When I execute the macro, the scene stays the same. But the Filter Controls Settings dialog has the updated settings when I open it.

When I reload the scene, it gets instant red.

I can then execute the macro and the scene goes back to normal.

But if I execute it again, again no visual change of the scene.

For my players the scene always stays normal.

### Steps to Reproduce

1. Have a colorfilter on the scene.
2. Execute macro -> nothing happens.
3. Press F5 -> expected behavior happens (but only for the gm).

### Context

The macro works perfectly fine on scenes without the gamma:0.5 filter applied before the macro.

### Version

2.2.0

### Foundry VTT Version

9.242

### Operating System

Linux

### Browser / App

Native Electron App

### Game System

Vampire the Masquerade 5e

### Relevant Modules

Bug persists with all other modules deactivated.

**Comment by ghost91-** [comment]
Thanks for the report. I’ll take a look at this as soon as possible!

**Comment by Danii0206** [comment]
Thank you! :)

**Comment by ghost91-** [comment]
Still need to create a new release. I am currently working on fixing another bug. I'll push out a new release as soon as that is resolved.

**Comment by ghost91-** [comment]
@Danii0206 I created a release now, can you verify it works correctly for you now?

**Comment by Danii0206** [comment]
In FXmaster 2.2.1 the issue is still there, nothing changed.

**Comment by Danii0206** [comment]
I made a video where I show the issue

https://user-images.githubusercontent.com/43935788/149775727-4ca66628-33a2-458d-a9ff-d1e6be026f59.mp4

.

**Comment by ghost91-** [comment]
OK, somehow a small part of the fix i made got lost at some point. No idea how that happened, sorry for that. I just created a new release that fixes that. Please check again @Danii0206.

**Comment by Danii0206** [comment]
Works like a charm now. Thank you! :D
